name: another test

on: push

jobs:
  do-something:
    runs-on: ubuntu-22.04
    steps:
      - name: step1
        run: |
          echo "1"
          pwd
          ls -a
        shell: bash
      - name: step2
        uses: actions/checkout@v6
      - name: step3
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          echo "hi there"
          pwd
          ls -a
